on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true
      file:
        description: File URL
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download file
        run: (new-object System.Net.WebClient).DownloadFile("${{ github.event.inputs.file }}","setup.exe")
      - name: Calculate checksum
        id: checksum
        run: echo "::set-output name=checksum::$((CertUtil -hashfile setup.exe SHA256)[1] -replace ' ','')"
      - name: Insert data
        run: |
          (Get-Content librewolf.nuspec).replace('{{version}}', '${{github.event.inputs.version}}') | Set-Content librewolf.nuspec
          (Get-Content tools/chocolateyinstall.ps1).replace('{{file}}', '${{github.event.inputs.file}}').replace('{{checksum}}', '${{steps.checksum.outputs.checksum}}') | Set-Content tools/chocolateyinstall.ps1
      - name: Create .nupkg
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      - name: Publish to chocolatey
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push librewolf.${{github.event.inputs.version}}.nupkg --source https://push.chocolatey.org/ -k ${{secrets.CHOCO_APIKEY}}
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.version }}"
          prerelease: false
          title: ${{github.event.inputs.version}}
          files: |
            librewolf.${{github.event.inputs.version}}.nupkg
